### ISSUE TITLE
Build from source on Linux Manjaro

### ISSUE THREAD

**Issue by CRY-D** [brackets-cont/brackets#111]
### Description

After following the [Building Brackets Releases](https://github.com/brackets-cont/brackets/wiki/Building-Brackets-Releases) instructions, this error appear after run `npm install`

![DeepinScreenshot_select-area_20211230172419](https://user-images.githubusercontent.com/16564491/147770446-613d1e69-ca2f-40b7-92b0-3d8b71f60656.png)

### Versions
OS: **Linux 5.12.19-1 MANJARO**
Node: **v17.2.0**
Npm  **v3.10.10**
Brackets: **2.0.1 source**

**Comment by charlypa** [comment]
@CRY-D 
Try building with node version 6 to see if it works.

We have not tested this version of brackets with Linux.

**Comment by abose** [comment]
Related to: https://github.com/brackets-cont/brackets/issues/110 

Thanks for raising the issue. We are with the Linux community on this and are working on top priority for a Linux port. 
Adobe had ditched support for Linux in its final build of brackets and I'm afraid it is due to a CEF platform limitation with the older CEF builds that Adobe used for brackets.
The Brackets community is now working on a larger platform migration to move away from CEF-based brackets-shell for Linux support. We expect to complete it by March 2022 and will have Linux builds for most Linux flavors soon after.
More details can be found here: https://github.com/brackets-cont/brackets/issues/26

Closing as we do not plan to support brackets shell builds in the future after electron port

follow #26 for electron migration status

**Comment by abose** [comment]
****

**Comment by CRY-D** [comment]
> @CRY-D Try building with node version 6 to see if it works.
> 
> We have not tested this version of brackets with Linux.

same issue, so i will wait til the end of march 2022

**Comment by kuohuanhuan** [comment]
**SAME ERROR** with
OS: Arch Linux (Kernel: 5.18.1)
Node.js: v16.15.1 LTS
NPM: v8.10.0 (Also tried w/ Yarn v1.22.18)
Brackets: 2.0.1 source
