### ISSUE TITLE
General Question: Is this project considered very Active still?

### ISSUE THREAD

**Issue by inglesuniversal** [brackets-cont/brackets#177]
Hello,

I was a big fan of brackets when it was handled and maintained by Adobe.

I stopped using it when Abode notified about dropping this project about two or three years ago.

What is the current road map for this project at this time, are there enough backers and maintainers to keep it alive and keep adding the kind of upgrades that made it special for me back then?

Thanks and I sincerely wish to be taking part of the NEW journey, if that is part of the new plans and future still to be written by this amazing and very useful IDE.

Best regards,

Hugo Barbosa

**Comment by TheMTtakeover** [comment]
I think the main focus of the team currently is https://github.com/brackets-cont/brackets/issues/26

**Comment by abose** [comment]
Hello @inglesuniversal The project is very active. The brackets community has expanded since adobe into a sister project as well: https://phcode.dev , the source lives at https://github.com/phcode-dev/

Phoenix marks the first large-scale, truly independent release from the Brackets community. Entirely homegrown within the community, it is also the [largest engineering effort put into Brackets](https://github.com/phcode-dev/phoenix/graphs/code-frequency) since 2015 (including Adobe).

Phoenix gives a glimpse of our future direction. Brackets is built to be the best code editor for the Web. Phoenix reinforces that direction by helping developers write code in the same browser environment they plan to deploy. The main focus currently in Phoenix is to enhance live preview, extensions store, and code intelligence in the coming weeks.

The next version of Brackets, 3.0, will be based on the Phoenix code base hosted in electron. Phoenix has done extensive groundwork to modernize brackets to the latest browser technologies. The shared code base will also benefit from faster development, sharing features, and extensions between Brackets and Phoenix.

## More links on what we are doing:
1. https://www.reddit.com/r/brackets/comments/tz06tn/brackets_community_announcement_phoenix_code/
2. https://github.com/phcode-dev/phoenix/issues
3. https://github.com/phcode-dev/phoenix/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement

**Comment by inglesuniversal** [comment]
Thanks so much for sharing these great News! LOVE to be back and whatever I can do to contribute (ideas, testing or improvements), I'll be more than happy to collaborate.

Best regards to every member who has made this project continue and shine for years to come!

Hugo Barbosa
