### ISSUE TITLE
Missing OS installers

### ISSUE THREAD

**Issue by ScanuNicco** [brackets-cont/brackets#9]
The releases on this repo only have the source code, not the windows and mac installers. Is this intentional or did something break because of the fork?

![image](https://user-images.githubusercontent.com/30136040/126880418-65df18ba-b406-4940-bbe6-3d09f8f928b2.png)
*Release 1.14.2 on the adobe/brackets repo*

![image](https://user-images.githubusercontent.com/30136040/126880429-cb54f641-c9e8-429d-84a2-108c1e01ce0f.png)
*Release 1.14.2 on this repo*

**Comment by Maniues** [comment]
It's because of the fork. Github doesn't transfer binary assets or other files (except for source code). 
Second Screenshot shows standard git tags. Github release it's github (not git) function. Github doesn't transfer this feature to forks (release).
Because it's fork and community-driven project, you can ask for binaries or make a google drive folder and send it here or send a pull request with edited README, to make binaries available for other people.

**Comment by ScanuNicco** [comment]
It looks like this might resolve itself when we figure out what we're going to do with Travis CI / Github Actions, so i'm going to close this for now.
